### ISSUE TITLE
v1.0.0版本中，打包的ol-plot.esm.js导入到vue2

### ISSUE THREAD

**Issue by daihaoran1** [sakitam-fdd/ol-plot#24]

**Comment by daihaoran1** [comment]
通过import olPlot from "./ol-plot.esm"导入后实例化  this.plot = new olPlot(this.map, { zoomToExtent: true });， 进而调用   this.plot.plotDraw.active(‘TriangleFlag’); 报错说


Uncaught TypeError: Class constructor Polygon cannot be invoked without 'new'
    at new TriangleFlag (ol-plot.esm.js:3432:1)
    at PlotDraw.createPlot (ol-plot.esm.js:3708:1)
    at PlotDraw.mapFirstClickHandler (ol-plot.esm.js:3805:1)
    at Map.dispatchEvent (Target.js:114:1)
    at Map.handleMapBrowserEvent (Map.js:1137:1)
    at MapBrowserEventHandler.dispatchEvent (Target.js:114:1)
    at MapBrowserEventHandler.emulateClick_ (MapBrowserEventHandler.js:134:1)
    at MapBrowserEventHandler.handlePointerUp_ (MapBrowserEventHandler.js:227:1)
TriangleFlag @ ol-plot.esm.js:3432
createPlot @ ol-plot.esm.js:3708
mapFirstClickHandler @ ol-plot.esm.js:3805
dispatchEvent @ Target.js:114
handleMapBrowserEvent @ Map.js:1137
dispatchEvent @ Target.js:114
emulateClick_ @ MapBrowserEventHandler.js:134
handlePointerUp_ @ MapBrowserEventHandler.js:227

**Comment by daihaoran1** [comment]
非常希望博主能给与解答

**Comment by sakitam-fdd** [comment]
方便使用 https://stackblitz.com/edit/vitejs-vite-q2dkvk?file=src%2Fmain.ts 给个最小示例吗，包括给出使用的 ol 版本

**Comment by daihaoran1** [comment]
您好，我已经解决好了，主要是代码打包时未采用es5模式打包，我在babel.config.js中添加了modules: false，打包后的js文件既可以再vue中采用import方式导入使用

**Comment by sakitam-fdd** [comment]
IE 已经退出历史舞台了，可以考虑放弃 es5 了
